/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.BookShop.PlaceOrder.View;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.BookShop.PlaceOrder.Controller.CustomerController;
import lk.BookShop.PlaceOrder.Controller.MainFormController;
import lk.BookShop.PlaceOrder.model.Customer;
import lk.BookShop.PlaceOrder.model.Item;
import lk.BookShop.PlaceOrder.model.ItemOrder;
import lk.BookShop.PlaceOrder.model.OrderDetail;

/**
 *
 * @author Ravishka Chandimal
 */
public final class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    String empId = "emp1";

    public MainForm() {
        try {
            initComponents();
            LoadAllCustomerIds();
            LoadAllItemIds();
            setOrderId();
            loadDateAndTime();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        BtnCustomer = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtCustid = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCustname = new javax.swing.JTextField();
        txtTEL = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtItem = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtItemid = new javax.swing.JComboBox<>();
        txtAbout = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtUnitPrice = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtOrderId = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        txtQtyOnHand = new javax.swing.JTextField();
        txttotal1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        lblValidation = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtDiscount1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTbl = new javax.swing.JTable();
        txtCash = new javax.swing.JTextField();
        btnPlaceOrder = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        txtDiscount = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lblFinelTotal = new javax.swing.JLabel();
        lblBallence = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(30, 55, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(44, 44, 84));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/BookShop/PlaceOrder/image/appbar.user.tie.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 140, 60));

        BtnCustomer.setBackground(new java.awt.Color(44, 44, 84));
        BtnCustomer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnCustomer.setForeground(new java.awt.Color(255, 255, 255));
        BtnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/BookShop/PlaceOrder/image/appbar.user.add.png"))); // NOI18N
        BtnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 140, 60));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Add Employee");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Add Item");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Search");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jButton5.setBackground(new java.awt.Color(44, 44, 84));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/BookShop/PlaceOrder/image/appbar.power.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 60, 60));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("log out and exit");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, -1, -1));

        jButton8.setBackground(new java.awt.Color(44, 44, 84));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/BookShop/PlaceOrder/image/appbar.money.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 140, 60));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("And settings");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 110, 30));

        jButton3.setBackground(new java.awt.Color(44, 44, 84));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/BookShop/PlaceOrder/image/appbar.section.expand.all.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 140, 60));

        jButton10.setBackground(new java.awt.Color(44, 44, 84));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/BookShop/PlaceOrder/image/appbar.page.search.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 140, 60));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Add Customer");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Buissness Details ");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));

        jPanel3.setBackground(new java.awt.Color(56, 103, 214));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCustid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCustid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtCustidItemStateChanged(evt);
            }
        });
        txtCustid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustidActionPerformed(evt);
            }
        });
        jPanel3.add(txtCustid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CustID");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("CustName");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 17, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tel");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 17, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Address");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, 30));

        txtCustname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(txtCustname, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 20, 170, 30));

        txtTEL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(txtTEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 20, 200, -1));

        txtAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 11, 349, 58));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 1120, 80));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText(" Item");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 40, 20));

        txtItem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(txtItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 140, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("ItemID");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("QTY ON HAND");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        txtItemid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtItemid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtItemidItemStateChanged(evt);
            }
        });
        jPanel4.add(txtItemid, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 140, -1));

        txtAbout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(txtAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, 133, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("BRAND");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 100, -1, -1));

        txtBrand.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 100, 133, -1));

        txtQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtyKeyTyped(evt);
            }
        });
        jPanel4.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 60, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Discount For Each Item");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("ABOUT");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 87, -1, 40));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("unitPrice");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        txtUnitPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtUnitPrice.setForeground(new java.awt.Color(255, 0, 0));
        txtUnitPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitPriceActionPerformed(evt);
            }
        });
        jPanel4.add(txtUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 140, 40));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("orderid");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("time");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        txtOrderId.setEditable(false);
        txtOrderId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(txtOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 140, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("date");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        txtdate.setEditable(false);
        txtdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });
        jPanel4.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 133, -1));

        txtTime.setEditable(false);
        txtTime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 140, -1));

        txtQtyOnHand.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(txtQtyOnHand, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 133, -1));

        txttotal1.setEditable(false);
        txttotal1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(txttotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 150, 40));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("QTY");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        lblValidation.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblValidation.setForeground(new java.awt.Color(255, 0, 0));
        jPanel4.add(lblValidation, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 140, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("TOTAL");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, -1));

        txtDiscount1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiscount1KeyReleased(evt);
            }
        });
        jPanel4.add(txtDiscount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 170, 120, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 1120, 240));

        jPanel5.setBackground(new java.awt.Color(56, 103, 214));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTbl.setBackground(new java.awt.Color(153, 153, 255));
        tblTbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ORDER ID", "CUST ID", "ITEM ID", "ITEM NAME", "QTY", "UNIT PRICE", "Discount", "Total"
            }
        ));
        tblTbl.setGridColor(new java.awt.Color(0, 204, 255));
        tblTbl.setSelectionBackground(new java.awt.Color(153, 153, 255));
        tblTbl.setSelectionForeground(new java.awt.Color(51, 51, 255));
        jScrollPane1.setViewportView(tblTbl);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1010, 170));

        txtCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCashActionPerformed(evt);
            }
        });
        txtCash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCashKeyReleased(evt);
            }
        });
        jPanel5.add(txtCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 130, 30));

        btnPlaceOrder.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        jPanel5.add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 250, 50));

        btnRemove.setBackground(new java.awt.Color(255, 51, 51));
        btnRemove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel5.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 80, 90, 30));

        btnAdd.setBackground(new java.awt.Color(102, 255, 102));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel5.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, 90, 30));

        jButton9.setBackground(new java.awt.Color(102, 102, 255));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("Update");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 150, 90, 30));

        txtDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscountActionPerformed(evt);
            }
        });
        txtDiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiscountKeyReleased(evt);
            }
        });
        jPanel5.add(txtDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 130, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Discount");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 80, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Cash");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        lblFinelTotal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblFinelTotal.setText("Total=00.00/=");
        jPanel5.add(lblFinelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, -1, -1));

        lblBallence.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblBallence.setText("Ballence=00.00/=");
        jPanel5.add(lblBallence, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 230, 50));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 1120, 280));

        jPanel2.setBackground(new java.awt.Color(30, 55, 153));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Book Shop Management System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 1120, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        int selectedRow = tblTbl.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblTbl.getModel();
        model.removeRow(selectedRow);
        calclulateTotal();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed
    private int isAlreadyExists(String code) {
        DefaultTableModel model = (DefaultTableModel) tblTbl.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            String temp = model.getValueAt(i, 2).toString();
            if (temp.equalsIgnoreCase(code)) {
                return i;
            }

        }
        return -1;
    }

    private void calclulateTotal() {
        DefaultTableModel model = (DefaultTableModel) tblTbl.getModel();

        double tempTotal = 0;

        for (int i = 0; i < model.getRowCount(); i++) {
            tempTotal += (Double) model.getValueAt(i, 7);
        }

        lblFinelTotal.setText(tempTotal + "");

    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblTbl.getModel();

        int Qty = Integer.parseInt(txtQty.getText());
        Double UnitPrice = Double.parseDouble(txtUnitPrice.getText());
        Double Total = Qty * UnitPrice;
        int discount = Integer.parseInt(txtDiscount1.getText());

        int rowIndex = isAlreadyExists(txtItemid.getSelectedItem().toString());

        if (rowIndex == -1) {
            Object[] rowData = {
                txtOrderId.getText(),
                txtCustid.getSelectedItem().toString(),
                txtItemid.getSelectedItem().toString(),
                txtItem.getText(),
                Qty,
                UnitPrice,
                discount,
                Total
            };
            model.addRow(rowData);

        } else {
            Qty += (int) model.getValueAt(rowIndex, 4);
            Total = Qty * UnitPrice;
            tblTbl.setValueAt(Qty, rowIndex, 4);
            tblTbl.setValueAt(Total, rowIndex, 6);

        }
        calclulateTotal();

    }//GEN-LAST:event_btnAddActionPerformed

    private void txtCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCashActionPerformed

    private void txtCustidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustidActionPerformed

    private void txtCustidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtCustidItemStateChanged
        try {
            Customer c1 = new CustomerController().getCustomer(txtCustid.getSelectedItem().toString());
            if (c1 != null) {
                txtCustname.setText(c1.getName());
                txtTEL.setText(c1.getTel() + "");
                txtAddress.setText(c1.getAddress());
            } else {
                JOptionPane.showMessageDialog(this, "try again");

            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtCustidItemStateChanged

    private void txtDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiscountActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void BtnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCustomerActionPerformed
        new AddCustomerForm().setVisible(true);
    }//GEN-LAST:event_BtnCustomerActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JOptionPane.showMessageDialog(this, "Are you Sure That You Want To Exit And Logout");
        this.dispose();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new AddEmployeeForm().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void txtUnitPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitPriceActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        new SearchForm().setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void txtQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyReleased
        int tempQty = Integer.parseInt(txtQty.getText());
        txttotal1.setText((tempQty * Double.parseDouble(txtUnitPrice.getText())) + "/=");

    }//GEN-LAST:event_txtQtyKeyReleased

    private void txtItemidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtItemidItemStateChanged
        try {
            Item T1 = new MainFormController().getItem(txtItemid.getSelectedItem().toString());
            if (T1 != null) {
                txtItem.setText(T1.getItemName());
                txtQtyOnHand.setText(T1.getItemQTY() + "");
                txtAbout.setText(T1.getDescr());
                txtBrand.setText(T1.getBrand());
                txtUnitPrice.setText(T1.getUnitPrice() + "");

            } else {
                JOptionPane.showMessageDialog(this, "try agin");

            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtItemidItemStateChanged

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblTbl.getModel();
        List<ItemOrder> list = new ArrayList<>();
        for (int i = 0; i < model.getRowCount(); i++) {
            String itemId = (String) model.getValueAt(i, 2);
            String orderid = (String) model.getValueAt(i, 0);
            int Qty = (int) model.getValueAt(i, 4);
            double Total = (double) model.getValueAt(i, 7);
            int discount = (int) model.getValueAt(i, 6);
            list.add(new ItemOrder(itemId, orderid, Qty, Total, discount));
        }
        double total = Double.parseDouble(lblFinelTotal.getText());
        new MainFormController().placeOrder(new OrderDetail(txtOrderId.getText(), txtCustid.getSelectedItem().toString(), empId, total, txtdate.getText(), list));

        try {
            setOrderId();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void txtQtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyPressed
        try {
            int i = Integer.parseInt(txtQty.getText());
            lblValidation.setText("");
        } catch (NumberFormatException ex) {
            lblValidation.setText("Invalid Number");
        }
    }//GEN-LAST:event_txtQtyKeyPressed

    private void txtQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyTyped

    }//GEN-LAST:event_txtQtyKeyTyped

    private void txtCashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCashKeyReleased
        DefaultTableModel model = (DefaultTableModel) tblTbl.getModel();

        double tempTotal = 0;
        double Cash = Double.parseDouble(txtCash.getText());

        for (int i = 0; i < model.getRowCount(); i++) {
            tempTotal += (Double) model.getValueAt(i, 7);
        }
        lblBallence.setText("Ballence : " + (Cash - tempTotal) + "/=");

    }//GEN-LAST:event_txtCashKeyReleased

    private void txtDiscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscountKeyReleased
        boolean empty = txtDiscount.getText().isEmpty();
        if (empty) {
            calclulateTotal();
        } else {

            double disc = Double.parseDouble(txtDiscount.getText());
            if (disc > 0) {
                DefaultTableModel model = (DefaultTableModel) tblTbl.getModel();

                double tempTotal = 0;
                double discount = Double.parseDouble(txtDiscount.getText());

                for (int i = 0; i < model.getRowCount(); i++) {
                    tempTotal += (Double) model.getValueAt(i, 7);
                }

                lblFinelTotal.setText("Total : " + (tempTotal - (tempTotal / 100 * discount)) + "/=");
            }
        }


    }//GEN-LAST:event_txtDiscountKeyReleased

    private void txtDiscount1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscount1KeyReleased

        double discountTotal = Integer.parseInt(txtQty.getText()) * Double.parseDouble(txtUnitPrice.getText());
        boolean empty = txtDiscount1.getText().isEmpty();
        int discount = Integer.parseInt(txtDiscount1.getText());
        if (empty) {
            txtQtyKeyReleased(evt);
        } else {
            txttotal1.setText((discountTotal - (discountTotal / 100 * discount)) + "");
        }
    }//GEN-LAST:event_txtDiscount1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCustomer;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBallence;
    private javax.swing.JLabel lblFinelTotal;
    private javax.swing.JLabel lblValidation;
    private javax.swing.JTable tblTbl;
    private javax.swing.JTextField txtAbout;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCash;
    private javax.swing.JComboBox<String> txtCustid;
    private javax.swing.JTextField txtCustname;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtDiscount1;
    private javax.swing.JTextField txtItem;
    private javax.swing.JComboBox<String> txtItemid;
    private javax.swing.JTextField txtOrderId;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtQtyOnHand;
    private javax.swing.JTextField txtTEL;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtUnitPrice;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txttotal1;
    // End of variables declaration//GEN-END:variables

    public void LoadAllCustomerIds() throws ClassNotFoundException, SQLException {

        for (String temp : new CustomerController().LoadAllCustomerIds()) {
            txtCustid.addItem(temp);
        }
    }

    public void LoadAllItemIds() throws ClassNotFoundException, SQLException {

        for (String temp : new MainFormController().LoadAllItemIds()) {
            txtItemid.addItem(temp);

        }

    }

    private void setOrderId() throws ClassNotFoundException, SQLException {
        String orderId = new MainFormController().getOrderId();

        if (orderId != null) {
            String[] temparr = orderId.split("OR");
            int tempNumber = Integer.parseInt(temparr[1]);
            tempNumber += 1;

            if (tempNumber < 10) {
                txtOrderId.setText("OR00" + tempNumber);
            } else {
                txtOrderId.setText("OR0" + tempNumber);
            }

        } else {
            txtOrderId.setText("O001");
        }

    }

    private void loadDateAndTime() {
        Date d1 = new Date();
        SimpleDateFormat format1 = new SimpleDateFormat("yyyy-mm-dd");
        txtdate.setText(format1.format(d1));

        SimpleDateFormat format2 = new SimpleDateFormat("HH:mm:ss");
        txtTime.setText(format2.format(d1));

    }

}
